enum StatusEnums {
  INITIAL_STATE,
  ORDER_UPDATED_STATE,
  PASSWORD_RESETTED_STATE,
  API_DATA_LOADED,
  SINGED_UP_STATE,
  ERROR_STATE,
  ORDERS_LOADED_STATE,
  LOADING_STATE,
  PROFILE_INFO_LOADED_STATE,
  ORDERS_ADDED_STATE,
  PROFILE_INFO_UPDATED_STATE,
  DRESS_LOADED_STATE,
  SLIDER_IMAGES_LOADED_STATE,
  PROFILE_IMAGE_UPDATED_STATE,
  PROFILE_PIC_GETTED_STATE,
  PROFILE_PIC_UPLOADING_STATE
}
